### ISSUE TITLE
"status":105,"value":"error":"element not interactable"

### ISSUE THREAD

**Issue by venkatrao-rgare** [react-native-windows/selenium-appium#31] opened 2020-04-15 03:45 UTC
The element is visible on the screen, but when I try to enter values in the field I am getting this error, 
```POST /wd/hub/session/F0992F7D-C9A0-4E23-AD13-DC1135F301E2/element/955a1a11-d2d5-4f2a-b322-ffa237920bfc/click HTTP/1.1
Accept: application/json; charset=utf-8
Connection: close
Content-Length: 2
Content-Type: application/json;charset=UTF-8
Host: localhost:4723
User-Agent: selenium/4.0.0-alpha.7 (js windows)
{}
HTTP/1.1 400 Bad Request
Content-Length: 175
Content-Type: application/json
{"status":105,"value":{"error":"element not interactable","message":"An element command could not be completed because the element is not pointer- or keyboard interactable."}}
```

also tried force clicking the element based on the previous issue I raised - https://github.com/react-native-windows/selenium-appium/issues/30
still the same result.

```import {Command} from 'selenium-webdriver/lib/command';
let cmd = new Command('legacyAction:click');
        cmd.setParameter('id', this.quotesNotesTab_ActionCode);
        await driver.execute(cmd);
        ```
Would appreciate some guidance on this on how to proceed further for troubleshooting this.

**Comment by licanhua** [comment] 2020-04-16 05:01
Are you using WinAppDriver, and what's your app type: UWP, WPF, Win32? Is the element an button or text?
I think there are a lot of case will result into this error:
1. Some element is not clickable. for example, textblock.
2. the element is disabled or it doesn't accept focus. You can easily verify it manually
3. the element is hidden or below an clickable element.
4. some element doesn't accept input, but its parent does
5. the element is not fully loaded yet when you click it
6. element is out of 'screen'. for example, you have two monitors. 

Below steps may help you to narrow down the problem:
1. If it's not 100% failure, it may related to timing, and you may fix it by wait for some time
2. try to reproduce it by manual procedure.
3, try the press/touch other than click.
4, try other action like settext, sendkeys

**Comment by venkatrao-rgare** [comment] 2020-04-21 16:33
Thanks for the steps to troubleshoot and apologies for the late reply.

What worked was this, 

 `this.driver.findElement(By2.nativeAccessibilityId("xxx")).findElement(By2.nativeName("yyy"));`

This didn't work

 `this.driver.findElement(By2.nativeName("yyy"));`

Leaving the answer here just in case someone need it.

**Comment by licanhua** [comment] 2020-05-05 21:14
I think it's winappdriver bug. I close this since it works for you

**Closed by licanhua** 2020-05-05 21:14 UTC
